apiVersion: '2018-10-01'
location: westeurope
name: elasticsearch
properties:
  containers:
  - name: elasticsearch-server
    properties:
      environmentVariables: []
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
      ports:
      - port: 80
      - port: 9200
      - port: 9300
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
      volumeMounts:
      - mountPath: /usr/share/elasticsearch/config/
        name: configs
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
      - port: 80
      - port: 9200
      - port: 9300
    dnsNameLabel: elasticsearch
  volumes:
  - name: configs
    azureFile:
      sharename: ${sharename}
      storageAccountName: ${accountName} 
      storageAccountKey: ${accountKey}
tags: {}
type: Microsoft.ContainerInstance/containerGroups
