version: '3.7'
services:
    dbserver:
        image:  mysql/mysql-server:8.0
        container_name: dbserver
        hostname: dbserver
        networks:
            - blogs
        # open ports to host for testing 
        ports:
            - 33060:3306
        env_file: ./env/.testEnv

        volumes:
            - ./data/mysql:/var/lib/mysql

    elasticsearch-server:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
        hostname: elasticsearch-server
        container_name: elasticsearch-server
        networks:
            - blogs
        ports:
            - 9200:9200
            # - 9300:9300
        user: elasticsearch
        volumes:
            # - ./esconfig/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            # - ./esconfig:/usr/share/elasticsearch/config
            # [WARN] Folders in host must be configure as 775 regarding accessbility
            - ./data/es/data:/usr/share/elasticsearch/data
            - ./data/es/logs:/usr/share/elasticsearch/logs

        environment:
            - discovery.type=single-node
            - ES_PATH_CONF=/usr/share/elasticsearch/config
            # where the data is stored
            - path.data=/usr/share/elasticsearch/data
            - path.logs=/usr/share/elasticsearch/logs
        # command: tail -f /dev/null

    microblog:
        depends_on:
            - dbserver
            - elasticsearch-server
        image: lentychang/microblog:latest
        container_name: microblog
        hostname: microblog
        networks: 
            - blogs
        ports:
            - 8000:5000
        env_file: ./env/.testEnv
        volumes:
            - ../app:/home/microblog/app
            - ../config.py:/home/microblog/config.py
            - ../microblog.py:/home/microblog/microblog.py

        working_dir: /home/microblog
        user: microblog
        entrypoint: ./boot.sh
        # entrypoint: tail -f /dev/null

    redis-server:
        image: redis:3-alpine
        hostname: redis-server
        container_name: redis-server
        networks:
            - blogs
        ports:
            - 6379:6379
            - 9300:9300
        
        environment:
            - discovery.type=single-node
            - ES_PATH_CONF=/usr/share/elasticsearch/config
            # where the data is stored
            - path.data=/usr/share/elasticsearch/data
            - path.logs=/usr/share/elasticsearch/logs
        # command: tail -f /dev/null



networks:
    blogs:
        driver: bridge
